/**
 * Rule-based readers for the formulaic parts of Indian bank mail. Anything
 * they can't read confidently falls through to Gemini, so these only need to
 * be precise, not complete. Every function is pure and unit-tested.
 */
import type { EmailMeta } from '../google/gmail';
import { parseLooseDate } from './dates';
import { emailAddress } from './text';

export interface HeuristicAlert {
  account_hint: string;
  account_kind: 'bank' | 'credit_card' | 'unknown';
  date: string;
  amount: string;
  direction: 'debit' | 'credit';
  narration: string;
  ref_no: string;
  institution: string;
}

/** sender-domain fragment → institution */
const BANK_DOMAINS: Array<[RegExp, string]> = [
  [/hdfcbank/i, 'HDFC Bank'],
  [/icicibank/i, 'ICICI Bank'],
  [/axisbank/i, 'Axis Bank'],
  [/sbicard/i, 'SBI Card'],
  [/sbi\.co\.in|onlinesbi|\bsbi\b/i, 'SBI'],
  [/kotak/i, 'Kotak Mahindra Bank'],
  [/yesbank/i, 'YES Bank'],
  [/idfcfirst|idfcbank/i, 'IDFC FIRST Bank'],
  [/indusind/i, 'IndusInd Bank'],
  [/federalbank/i, 'Federal Bank'],
  [/rblbank/i, 'RBL Bank'],
  [/americanexpress|amex/i, 'American Express'],
  [/citi(bank|\.com)/i, 'Citi'],
  [/hsbc/i, 'HSBC'],
  [/sc\.com|standardchartered/i, 'Standard Chartered'],
  [/aubank/i, 'AU Small Finance Bank'],
  [/bankofbaroda|bobcard/i, 'Bank of Baroda'],
  [/pnb\.|pnbindia/i, 'Punjab National Bank'],
  [/canarabank/i, 'Canara Bank'],
  [/unionbank/i, 'Union Bank of India'],
  [/onecard|getonecard/i, 'OneCard'],
  [/sliceit|slice/i, 'Slice'],
  [/jupiter\.money/i, 'Jupiter'],
  [/fi\.money|epifi/i, 'Fi'],
  [/niyo/i, 'Niyo'],
  [/dbs\.com|dbsbank/i, 'DBS Bank'],
  [/bandhanbank/i, 'Bandhan Bank'],
  [/idbi/i, 'IDBI Bank'],
  [/unionbankofindia/i, 'Union Bank of India'],
];
const BANK_NAMES = /\b(HDFC|ICICI|Axis|SBI|State Bank of India|Kotak|YES|IDFC(?: FIRST)?|IndusInd|Federal|RBL|American Express|Amex|Citi(?:bank)?|HSBC|Standard Chartered|AU Small Finance|Bank of Baroda|PNB|Canara|Union Bank|OneCard|Slice|Jupiter|Fi|Niyo|DBS|Bandhan|IDBI)\b/i;
/** Card-bill payment confirmations (CRED, PhonePe, bank apps): a credit on the card that was paid. */
const CARD_BILL_PAID = /\b(?:credit card bill|card bill|bill payment)\b[^.]{0,60}\b(?:successful|paid|received|done|complete)|\bpaid\b[^.]{0,40}\b(?:credit card|card) bill\b|\bbill payment (?:was |is )?successful\b/i;

export function institutionOf(from: string, text: string): string {
  const addr = emailAddress(from);
  for (const [re, name] of BANK_DOMAINS) if (re.test(addr)) return name;
  const m = BANK_NAMES.exec(`${from} ${text}`);
  if (!m) return '';
  const n = m[1]!;
  if (/^(sbi|state bank of india)$/i.test(n)) return /sbi card|credit card/i.test(text) ? 'SBI Card' : 'SBI';
  return /bank$/i.test(n) || /express|citi|hsbc|chartered|onecard|slice|jupiter|niyo|dbs|card/i.test(n) ? n : `${n} Bank`;
}

const NOT_A_TXN =
  /\b(OTP|one[- ]time password|declined|unsuccessful|has failed|could not be processed|reversal request|login|password reset|e-?mandate registration|autopay (?:set|registered)|offer|reward points|cashback offer|pre-?approved|fixed deposit|\bFD\b|term deposit|renew(?:al|ed)?|matur(?:es|ity|ed)|sum (?:assured|insured)|will be (?:debited|credited|deducted)|scheduled|upcoming|reminder|due on)\b/i;
const DEBIT_WORDS = /\b(debited|has a debit|debit (?:by|of|for)|spent|paid|withdrawn|purchase|payment of|sent|transferred|charged|used for (?:a )?(?:transaction|txn|purchase)|txn of|has been made)\b/i;
const CREDIT_WORDS = /\b(credited|has a credit|credit (?:by|of|for)|received|deposited|refund(?:ed)?|reversed|cashback of)\b/i;
/** Phrases that settle direction outright ("payment of Rs X received" is a credit despite "payment of"). */
const CREDIT_PHRASES =
  /\b(payment (?:of [^\n]{0,60}?)?(?:has been |was |is |towards [^\n]{0,60}?)?received|(?:have |has )?received (?:\w+ ){0,3}payment|payment (?:of [^\n]{0,60}?)?(?:has been |was |is )?credited|credited to your (?:\w+ ){0,4}(?:card|account|a\/c)|thank you for (?:your |the )?payment|dividend|interest credited|refund(?:ed)? (?:of|to)|cashback (?:of|credited)|credit(?:ed)? (?:of|for) (?:Rs|INR|₹))\b/i;
/** Footer / disclaimer text that must never become a merchant name. */
const DISCLAIMER = /\b(advice|recommendation|DICGC|confirmation message|confidential|unsubscribe|terms|regards|disclaimer|privacy|helpline|customer care|toll[- ]free|call us|write to|do not share|never share|this is (?:an? )?(?:system|auto)|autogenerated|no[- ]reply|insured up to)\b/i;
/** Only this much text around the amount is used for direction/merchant — footers stay out. */
const WINDOW = 260;
const AMOUNT_RE = /(?:Rs\.?|INR|₹)\s*(\d[\d,]*(?:\.\d{1,2})?)|(\d[\d,]*(?:\.\d{1,2})?)\s*(?:Rs\.?|INR)\b/gi;
const BALANCE_CONTEXT = /(?:bal(?:ance)?|limit|lmt|available|avl|avail|outstanding|total due|min(?:imum)? due|due amount)[^\d]{0,25}$/i;
/**
 * A masked account/card number: needs a masking marker (XX1234, **1234, X7310,
 * "ending 1234", "ending with 1234") — never a bare 4-digit number.
 */
const LAST4_RE = /(?:ending(?: with| in)?|last (?:four|4)(?: digits)?)\s*[:\-]?\s*(?:x+|\*+|•+)?\s*(\d{4,})\b|(?:\b(?:x{1,}|\*{2,}|•{2,})[\s-]?|(?:^|[^A-Za-z0-9])(?:x{1,}|\*{2,}|•{2,})(?:\s?-\s?|\s)?)(\d{4,})\b(?![\d,.]*(?:%|\.\d))/i;
/** The digits after a mask can be longer than 4 (SBI prints XXXXX097310): keep the last four. */
function last4Of(m: RegExpExecArray | RegExpMatchArray | null): string {
  const d = m ? (m[1] ?? m[2] ?? '') : '';
  return d.slice(-4);
}
const DATE_RE = /\b(\d{1,2}[-/][A-Za-z]{3}[-/]\d{2,4}|\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}(?:st|nd|rd|th)? [A-Za-z]{3,9},? \d{4}|[A-Za-z]{3,9} \d{1,2},? \d{4})\b/;
const REF_RE = /\b(?:(?:UPI|IMPS|NEFT|RTGS)\s+)?(?:Ref(?:erence)?\s*(?:No|Number|#|ID)?\.?|(?:RRN|UTR)\s*(?:No|Number)?\.?|Transaction (?:ID|Ref(?:erence)?)|Txn (?:ID|Ref|No)|\bref)\s*(?:is|:)?[:\s.-]*(?=[A-Z0-9]*\d)([A-Z0-9]{6,22})\b/i;
const MODE_RE = /\b(UPI|IMPS|NEFT|RTGS|ATM|POS|ECS|NACH|Auto ?Debit|EMI|Standing Instruction|SI)\b/i;
const STOP = String.raw`\s+(?:on|via|using|ref|upi|thru|through|from|with|at|to|towards|for|and|\d{1,2}[-/:])\b|\.(?:\s|$)|,|;|\(|\s*$`;
const NARR_TO = new RegExp(String.raw`\b(?:at|to|towards)\s+(?:VPA\s+)?([A-Za-z][^\n.,;(]{2,60}?)(?=${STOP})`, 'gi');
const NARR_FROM = new RegExp(String.raw`\bfrom\s+([A-Za-z][^\n.,;(]{2,60}?)(?=${STOP})`, 'gi');
const NARR_INFO = /\b(?:Info|Remarks?|Description|Narration)[:\s-]+([^\n.]{3,60})/gi;
const NARR_VPA = /\bVPA\s+([\w.\-]+@[\w]+)/gi;
const NARR_AFTER_DATE = /\bon \d{1,2}[-/]\d{1,2}[-/]\d{2,4}\s*[-:–]\s*([A-Za-z][^.\n]{2,50}?)(?=\.|\s+(?:Avl|Available|Bal)|$)/gi;
const NARR_PARTY = /\b(?:Sent by|Remitter(?: name)?|Payer|Beneficiary|Payee|Merchant|Paid to|Received from)\s*[:\-]\s*([A-Za-z][^\n.,;(]{2,60}?)(?=\s+(?:Sender|Bank|IFSC|UTR|Ref|Date|Amount)\b|\.|,|;|$)/gi;
const NARR_FOR = new RegExp(String.raw`\bfor\s+([A-Za-z][^\n.,;(]{2,60}?)(?=${STOP})`, 'gi');
const NARR_MODE = /\b(?:debit|credit|debited|credited) by ([A-Z]{2,6}(?:\/[A-Z]{2,6})?)\b/gi;
const NARR_JUNK =
  /^(?:(?:your|the|you|this|a|an|transaction|txn|payment|purchase|inr|rs\.?|account|a\/c|card|vpa|cancel|block|report|dispute|call|sms|forward|reply|click|visit|log ?in|download|know more|details|help|assistance|queries|any|further|more|complete|confirm|verify|update|secure|safety|security|dear|greetings|customer|sbi ?!|state bank)\b|\d)/i;
const NARR_BAD_INSIDE = /\b(dear customer|greetings|do not reply|auto generated|toll free)\b/i;

function pickNarration(text: string, direction: 'debit' | 'credit'): string {
  const order = direction === 'credit' ? [NARR_PARTY, NARR_MODE, NARR_FROM, NARR_INFO, NARR_AFTER_DATE, NARR_TO, NARR_VPA, NARR_FOR] : [NARR_PARTY, NARR_TO, NARR_VPA, NARR_MODE, NARR_INFO, NARR_AFTER_DATE, NARR_FOR, NARR_FROM];
  for (const re of order) {
    for (const m of text.matchAll(re)) {
      const cand = m[1]!.trim().replace(/\s+/g, ' ');
      if (cand.length >= 3 && !NARR_JUNK.test(cand) && !NARR_BAD_INSIDE.test(cand) && !/^\d[\d,.]*$/.test(cand)) return cand.slice(0, 80);
    }
  }
  return '';
}

/** Strip masked numbers so the amount/date regexes can't latch onto XXXX1234 fragments. */
function cleanBody(text: string): string {
  return text.replace(/\s+/g, ' ').slice(0, 3000);
}

/**
 * Parse a transaction alert deterministically. Returns null unless amount,
 * direction, and account hint are all unambiguous — the LLM handles the rest.
 */
export function parseAlert(e: { from: string; subject: string; bodyText: string; receivedAt: string }): HeuristicAlert | null {
  const text = cleanBody(`${e.subject}. ${e.bodyText}`);
  if (NOT_A_TXN.test(text) && !/\b(debited|credited|spent)\b/i.test(e.subject)) return null;

  // amounts, ignoring balances/limits
  const amounts: Array<{ value: string; index: number }> = [];
  for (const m of text.matchAll(AMOUNT_RE)) {
    const value = (m[1] ?? m[2])!;
    if (BALANCE_CONTEXT.test(text.slice(Math.max(0, m.index! - 40), m.index!))) continue;
    if (!/\d/.test(value) || value.replace(/[^\d]/g, '').length < 1) continue;
    amounts.push({ value, index: m.index! });
  }
  const distinct = [...new Set(amounts.map((a) => a.value.replace(/,/g, '')))];
  if (distinct.length !== 1) return null;
  const amount = amounts[0]!;
  // Everything else is judged from the text around the amount, not the whole mail.
  const winStart = Math.max(0, amount.index - WINDOW);
  const win = text.slice(winStart, amount.index + WINDOW);
  const amountInWin = amount.index - winStart;

  // direction: decisive phrases first, else the word nearest the amount
  const near = (re: RegExp) => {
    let best = Infinity;
    for (const m of win.matchAll(new RegExp(re.source, 'gi'))) best = Math.min(best, Math.abs(m.index! - amountInWin));
    return best;
  };
  let direction: 'debit' | 'credit';
  const billPaid = CARD_BILL_PAID.test(text);
  if (billPaid || CREDIT_PHRASES.test(win)) direction = 'credit';
  else {
    const d = near(DEBIT_WORDS);
    const c = near(CREDIT_WORDS);
    if (d === Infinity && c === Infinity) return null;
    if (Math.abs(d - c) < 15 && d !== Infinity && c !== Infinity) return null; // "debited … credited" IMPS pair — let the model read it
    direction = d <= c ? 'debit' : 'credit';
  }

  // account
  const institution = institutionOf(e.from, text);
  const l4 = LAST4_RE.exec(text);
  const last4 = last4Of(l4);
  if (!institution && !last4) return null;
  const isCard = billPaid || /\b(credit card|debit card|card)\b/i.test(text.slice(Math.max(0, (l4?.index ?? amount.index) - 60), (l4?.index ?? amount.index) + 60));
  const account_kind: HeuristicAlert['account_kind'] = isCard ? 'credit_card' : /\b(a\/c|account|acct)\b/i.test(text) ? 'bank' : 'unknown';
  const account_hint = `${institution}${isCard ? ' Credit Card' : account_kind === 'bank' ? ' A/c' : ''}${last4 ? ` XX${last4}` : ''}`.trim();

  // date: first plausible date in text, else the email's own date
  const received = e.receivedAt.slice(0, 10);
  let date = received;
  const dm = DATE_RE.exec(text);
  if (dm) {
    const parsed = parseLooseDate(dm[1]!);
    if (parsed && parsed <= received && daysDiff(parsed, received) <= 35) date = parsed;
  }

  let narration = billPaid ? `Card bill payment${/\bCRED\b/i.test(`${e.from} ${text}`) ? ' via CRED' : ''}` : pickNarration(win, direction);
  if (narration && DISCLAIMER.test(narration)) narration = '';
  if (!narration) {
    // Bank-to-bank transfers name no merchant: fall back to "IMPS A/c XX9999".
    const mode = MODE_RE.exec(win)?.[1];
    const others = [...win.matchAll(new RegExp(LAST4_RE.source, 'gi'))].map((m) => last4Of(m)).filter((n) => n && n !== last4);
    if (!mode) {
      // Card-bill payments name no merchant either ("payment received … via CRED").
      const via = /\b(?:via|through|using)\s+([A-Za-z][A-Za-z0-9 .&-]{1,30}?)(?=\s*(?:on|\.|,|$))/i.exec(win)?.[1];
      if (/\bpayment\b/i.test(win)) narration = direction === 'credit' ? `Card payment received${via ? ` via ${via.trim()}` : ''}` : `Payment${via ? ` via ${via.trim()}` : ''}`;
      else return null;
    } else
    narration = `${mode.toUpperCase()}${others[0] ? ` A/c XX${others[0]}` : direction === 'debit' ? ' transfer' : ' credit'}`;
  }

  const ref = REF_RE.exec(text)?.[1] ?? '';
  return { account_hint, account_kind, date, amount: amount.value, direction, narration: narration.slice(0, 80), ref_no: ref, institution };
}

function daysDiff(a: string, b: string): number {
  return Math.abs(Date.parse(`${b}T00:00:00Z`) - Date.parse(`${a}T00:00:00Z`)) / 86400_000;
}

/** Statement delivery: a PDF from a bank with statement-ish words in the subject or filename. */
export function detectStatement(e: { from: string; subject: string; attachments: Array<{ filename: string; mimeType: string }> }): 'cc_statement' | 'bank_statement' | null {
  const pdf = e.attachments.some((a) => /pdf/i.test(a.mimeType) || /\.pdf$/i.test(a.filename));
  if (!pdf) return null;
  const text = `${e.subject} ${e.attachments.map((a) => a.filename).join(' ')}`;
  if (!/\b(statement|e-?statement|stmt)\b/i.test(text)) return null;
  if (!institutionOf(e.from, text)) return null;
  return /\b(credit card|card statement|card)\b/i.test(text) ? 'cc_statement' : 'bank_statement';
}

export interface HeuristicBill {
  card_hint: string;
  total_due: string;
  min_due: string;
  due_date: string;
  statement_date: string;
}

/** Card bill summary in an email body ("Total Amount Due … Payment Due Date …"). */
export function parseBill(e: { from: string; subject: string; bodyText: string }): HeuristicBill | null {
  const text = cleanBody(`${e.subject}. ${e.bodyText}`);
  const total = /total (?:amount )?due[^\d₹R]{0,30}(?:Rs\.?|INR|₹)?\s*([\d,]+(?:\.\d{1,2})?)/i.exec(text)?.[1];
  const min = /min(?:imum)? (?:amount )?due[^\d₹R]{0,30}(?:Rs\.?|INR|₹)?\s*([\d,]+(?:\.\d{1,2})?)/i.exec(text)?.[1];
  const dueRaw = /(?:payment )?due (?:date|by|on)[^\d]{0,20}(\d{1,2}[-/ ][A-Za-z]{3}[-/ ,]*\d{2,4}|\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4}|[A-Za-z]{3,9} \d{1,2},? \d{4})/i.exec(text)?.[1];
  if (!total || !dueRaw) return null;
  const institution = institutionOf(e.from, text);
  const l4 = LAST4_RE.exec(text);
  const last4 = last4Of(l4);
  if (!institution && !last4) return null;
  const stmtRaw = /statement (?:date|dated|generated on)[^\d]{0,20}(\d{1,2}[-/ ][A-Za-z]{3}[-/ ,]*\d{2,4}|\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4}|[A-Za-z]{3,9} \d{1,2},? \d{4})/i.exec(text)?.[1];
  return {
    card_hint: `${institution} Credit Card${last4 ? ` XX${last4}` : ''}`.trim(),
    total_due: total,
    min_due: min ?? '',
    due_date: parseLooseDate(dueRaw) ?? '',
    statement_date: stmtRaw ? (parseLooseDate(stmtRaw) ?? '') : '',
  };
}

export interface HeuristicProposal {
  kind: 'bank' | 'credit_card';
  institution: string;
  last4: string;
  seen: number;
  statement_sender: string;
  example_subject: string;
}

const TXN_EVIDENCE = /\b(debited|credited|spent|statement|e-?statement|transaction alert|txn|payment (?:received|made|of)|bill (?:generated|due)|amount due|withdrawn|deposited|is ready|has been (?:used|made))\b/i;
const MARKETING = /\b(offer|pre-?approved|reward|voucher|contest|switch to|upgrade|refer|cashback offer|congratulations|exciting|milestone|festival|% ?off|sale|unlock|beware|awareness|tips|invitation|webinar|newsletter|introducing|loan\b|emi\b|insurance|mutual fund|portfolio|disclosure)\b/i;

/**
 * Account discovery from mail: the institution must come from the SENDER
 * (bank domains), the mail must look transactional and not like marketing,
 * and a masked number needs a masking marker. Statement mails count on their own.
 */
export function discoverHeuristically(emails: Array<Pick<EmailMeta, 'from' | 'subject' | 'snippet'> & { bodyText?: string; attachments?: Array<{ filename: string; mimeType: string }> }>): { proposals: HeuristicProposal[]; unresolved: number[] } {
  const found = new Map<string, HeuristicProposal>();
  const unresolved: number[] = [];
  emails.forEach((e, i) => {
    const text = `${e.subject} ${e.bodyText || e.snippet}`.replace(/\s+/g, ' ');
    const addr = emailAddress(e.from);
    let institution = '';
    for (const [re, name] of BANK_DOMAINS) if (re.test(addr)) institution = name;
    if (!institution) {
      if (/\b(debited|credited|statement)\b/i.test(text) && AMOUNT_RE.test(text)) unresolved.push(i);
      AMOUNT_RE.lastIndex = 0;
      return;
    }
    const isStatement = /\b(statement|e-?statement)\b/i.test(e.subject) && (e.attachments?.some((a) => /pdf/i.test(a.mimeType) || /\.pdf$/i.test(a.filename)) ?? true);
    if (!isStatement) {
      if (MARKETING.test(e.subject)) return;
      if (!TXN_EVIDENCE.test(text)) return;
      AMOUNT_RE.lastIndex = 0;
      if (!AMOUNT_RE.test(text)) return;
      AMOUNT_RE.lastIndex = 0;
    }
    const l4 = LAST4_RE.exec(text);
    const last4 = last4Of(l4);
    const near = l4 ? text.slice(Math.max(0, l4.index - 60), l4.index + 60) : text.slice(0, 200);
    const kind: HeuristicProposal['kind'] = /\bcredit card\b|card statement|\bcard\b/i.test(near) || /card/i.test(institution) ? 'credit_card' : 'bank';
    const key = `${institution.toLowerCase()}|${kind}|${last4}`;
    const cur = found.get(key);
    if (cur) {
      cur.seen++;
      if (!cur.statement_sender && isStatement) cur.statement_sender = addr;
    } else found.set(key, { kind, institution, last4, seen: 1, statement_sender: isStatement ? addr : '', example_subject: e.subject.slice(0, 70) });
  });
  const all = [...found.values()];
  // A numberless entry for an institution+kind that also has numbered ones is the same account seen without its number.
  const proposals = all
    .filter((p) => p.last4 || !all.some((q) => q !== p && q.last4 && q.institution === p.institution && q.kind === p.kind))
    .filter((p) => (p.last4 && (p.seen >= 2 || p.statement_sender)) || p.seen >= 3 || p.statement_sender)
    .sort((a, b) => b.seen - a.seen);
  return { proposals, unresolved };
}
